[phases.setup]
nixPkgs = ['nodejs-18_x', 'pnpm-9_x']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm run build']

[start]
cmd = 'pnpm run start'

[variables]
NODE_ENV = 'production'
